"""link events to issues

Revision ID: 4583a0302ac2
Revises: fc1ad349bcd8
Create Date: 2026-09-12 10:59:05.435368

"""
from alembic import op
import sqlalchemy as sa


revision = '4583a0302ac2'
down_revision = 'fc1ad349bcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'events',
        sa.Column('issue_id', sa.UUID(as_uuid=False), nullable=True)
    )

    op.create_foreign_key(
        'fk_events_issue_id',
        'events',
        'issues',
        ['issue_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_events_issue_id',
        'events',
        type_='foreignkey'
    )

    op.drop_column('events', 'issue_id')
    # ### end Alembic commands ###