"""initial tables

Revision ID: d9186479e68b
Revises: 
Create Date: 2026-09-12 10:46:40.337554

"""
from alembic import op
import sqlalchemy as sa


revision = 'd9186479e68b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_table('buses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('bus_code', sa.String(), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bus_code')
    )
    op.create_table('cameras',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('camera_code', sa.String(), nullable=False),
    sa.Column('bus_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_code')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bus_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('camera_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('cameras')
    op.drop_table('buses')
    op.drop_table('routes')
    # ### end Alembic commands ###
