"""add issues

Revision ID: fc1ad349bcd8
Revises: d9186479e68b
Create Date: 2026-09-12 10:50:09.138463

"""
from alembic import op
import sqlalchemy as sa


revision = 'fc1ad349bcd8'
down_revision = 'd9186479e68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'issues',
        sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('subtype', sa.String(), nullable=False),
        sa.Column('lat', sa.Float(), nullable=False),
        sa.Column('lng', sa.Float(), nullable=False),
        sa.Column('severity', sa.String(), nullable=True),
        sa.Column('priority', sa.Float(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('first_seen', sa.DateTime(), nullable=False),
        sa.Column('last_seen', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    # ### end Alembic commands ###